name: Yarn Cache

author: johngeorgewright

description: Speed up your Node.js builds by caching the Yarn dependencies.

inputs:
  cache_path:
    description: The cache paths
    default: |
      ~/.cache
      .yarn/unplugged
      .yarn/install-state.gz
  working-directory:
    description: Optional directory to execute in
    required: false

runs:
  using: composite
  steps:
    - id: key
      working-directory: ${{ inputs.working-directory }}
      shell: bash
      run: echo "cache-key=${{ runner.os }}-node-$(node --version)-yarn-$(yarn --version)-${{ hashFiles('**/yarn.lock') }}" >> $GITHUB_OUTPUT

    - id: cache
      uses: actions/cache@v4
      working-directory: ${{ inputs.working-directory }}
      with:
        path: ${{ inputs.cache_path }}
        key: ${{ steps.key.outputs.cache-key }}

    - if: steps.cache.outputs.cache-hit != 'true'
      working-directory: ${{ inputs.working-directory }}
      shell: bash
      run: yarn --imutable
