name: NPM Cache

author: johngeorgewright

description: Speed up your Node.js builds by caching the NPM dependencies.

inputs:
  cache_path:
    description: The cache paths
    default: |
      node_modules
  working-directory:
    description: Optional directory to execute in
    required: false

runs:
  using: composite
  steps:
    - id: key
      working-directory: ${{ inputs.working-directory }}
      shell: bash
      run: echo "cache-key=${{ runner.os }}-node-$(npm --version)-npm-$(npm --version)-${{ hashFiles('**/package-lock.json') }}" >> $GITHUB_OUTPUT

    - id: cache
      working-directory: ${{ inputs.working-directory }}
      uses: actions/cache@v4
      with:
        path: ${{ inputs.cache_path }}
        key: ${{ steps.key.outputs.cache-key }}

    - if: steps.cache.outputs.cache-hit != 'true'
      working-directory: ${{ inputs.working-directory }}
      shell: bash
      run: npm ci
