name: Nested worflow

# description: A workflow nested inside the .github directory

on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        run: echo "yay"