name: NPM Cache

on:
  workflow_call:
    inputs:
      runs-on: 
        default: dmg-arc-ubuntu
        required: false
        type: string
        description: Use runs-on to define the type of machine to run the job on.

    outputs:
      key:
        value: ${{ jobs.key.outputs.cache-key }}
      path:
        value: ${{ jobs.prime.outputs.cache-path }}

jobs:
  key:
    name: Key
    runs-on: ${{ inputs.runs-on }}
    outputs:
      cache-key: ${{ steps.key.outputs.cache_key }}
    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Install Node.js
        id: node
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc

      - name: Key
        id: key
        run: |
          echo "cache_key=${{ runner.os }}-node-${{ steps.node.outputs.node-version }}-npm-$(npm --version)-${{ hashFiles('**/package-lock.lock') }}" >> $GITHUB_OUTPUT

  prime:
    name: Prime
    needs: [key]
    runs-on: ${{ inputs.runs-on }}
    env:
      CACHE_PATH: |
        node_modules
    concurrency:
      group: ${{ needs.key.outputs.cache-key }}
    outputs:
      cache-path: ${{ env.CACHE_PATH }}
    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Install Node.js
        id: node
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc

      - name: Cache
        id: cache
        uses: actions/cache@v4
        with:
          path: ${{ env.CACHE_PATH }}
          key: ${{ needs.key.outputs.cache-key }}

      - name: Install Depedencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci
